apiVersion: v1
kind: Service
metadata:
  name: games
  namespace: games
  labels:
    app: games
spec:
  type: ClusterIP
  selector:
    app: games
  ports:
    - name: http
      port: 80
      targetPort: 80
